# oneX 主题配置文件

# 网站头部配置
head:
    # 网站图标 (favicon)
    favicon: "https://avatars.githubusercontent.com/u/62823553?s=48&v=4"

# 图片配置
img:
    # 头像图片，显示在首页欢迎卡片和文章卡片中
    avatar: "/img/avatar.png"
    # 首页左侧大图（欢迎卡片背景）
    left_pic: 
      - "/img/home.png"
    # 首页右侧 Logo 卡片图片
    right_pic:
      - "/img/right_pic.png"
    # 文章缩略图，支持多个随机显示
    post_thumbnail: 
      - "https://www.loliapi.com/acg/"
    # 侧边栏头部背景图
    drawerHeaderBg:
      - "/img/bnr-bakuen.png"

# UI/UX 配置
uiux:
    # 首页欢迎语，支持多个随机显示
    slogan: "为美好的世界献上祝福！"
    # 默认主题色
    defaultPrimaryColor: "blue"
    # 默认强调色
    defaultAccentColor: "red"
    # 是否显示全屏加载动画
    loading: true
    # 加载动画文字
    loadingText: "正在施放爆裂魔法..."
    # 是否显示回到顶部按钮
    backToTop: true
    # 是否显示自定义滚动条
    scrollbar: true
    # 是否显示文章目录
    toc: true
    # 搜索框占位文字
    searchPlaceholder: "在异世界寻找..."
    # 404 页面文字
    notFoundText: "Explosion！页面被惠惠炸没了..."

# 评论系统配置
comment:
    # Disqus 评论
    disqus:
        # Disqus shortname
        shortName: "novicelevel-github-io"

# 侧边栏菜单配置
# type: sitelink (站内链接), page (独立页面), link (外部链接), hr (分隔线)
Drawer:
    - title: 首页
      type: sitelink
      href: /
      icon: home
    - title: hr
      type: hr
    - title: 关于我
      type: page
      name: about
      icon: account_circle
    - title: 搜索
      type: sitelink
      href: /search/
      icon: search
    - title: 分类
      type: sitelink
      href: /categories
      icon: folder
    - title: 标签
      type: sitelink
      href: /tags
      icon: label

# 是否显示颜色选择器
colorPicker: true

# 首页工具栏菜单
homeToolBar:
  - icon: "more_vert"
    items:
      - title: RSS
        type: link
        href: /atom.xml
        icon: rss_feed

# 页脚配置
# 第一项为版权信息，第二项为随机显示的标语（数组）
footer:
  - "Copyright © 2026 KonoSuba"
  - - "为美好的世界献上祝福！"
    - "Explosion！爆裂魔法才是浪漫！"
    - "我的名字是惠惠！红魔族第一魔法使！"
    - "一天一发爆裂魔法，身体健康精神爽！"
    - "吾乃红魔族首屈一指的魔法师，操纵爆裂魔法之人！"
    - "爆裂魔法是艺术！是美学！是信仰！"
